version : 0.2

phases:
  install:
    commands:
      #install node
      - echo Instslling Node 12............
      - curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash - &&\
      - sudo apt-get install nodejs
  pre_build:
    commands:
      #install dependencies
      - echo Installing dependencies
      - npm install
  build:
    commands:
      #build
      - echo Building............
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths : no
  base-directory : dist